dataset_dir: '/gpfs/gibbs/pi/krishnaswamy_smita/cl2482/DirectedGNN/rewritten_LEGS/data/IMiD_smiles.npy'
save_dir: '/gpfs/gibbs/pi/krishnaswamy_smita/cl2482/DirectedGNN/rewritten_LEGS/trained_models/'
learning_rate: 1e-3
max_epochs: 100
batch_size: 32
patience: 5
num_workers: 0
random_seed: 1
train_val_test_ratio: '8:1:1'